"""Initial migration

Revision ID: bcb0399d85b2
Revises: 
Create Date: 2025-02-23 13:17:03.128848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcb0399d85b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=True))
        
        # Aggiunta di nomi ai vincoli di chiave esterna
        batch_op.create_foreign_key('fk_user_progress_challenge', 'challenge', ['challenge_id'], ['id'])
        batch_op.create_foreign_key('fk_user_progress_user', 'user', ['user_id'], ['id'])
        
        batch_op.drop_column('container_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('container_id', sa.VARCHAR(length=100), nullable=True))
        
        # Specificare il nome del vincolo per rimuoverlo correttamente
        batch_op.drop_constraint('fk_user_progress_challenge', type_='foreignkey')
        batch_op.drop_constraint('fk_user_progress_user', type_='foreignkey')
        
        batch_op.drop_column('score')

    # ### end Alembic commands ###
